export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_SINGLE_USERNAME = 'FETCH_SINGLE_USER'
export const FETCH_USER_TASKS = 'FETCH_USER_TASKS'
export const FETCH_USER_SINGLE_TASK = 'FETCH_USER_SINGLE_TASK'
